module.exports = {
  includedFields: null,
  excludedFields: null,
  includedProfileFields: null,
  excludedProfileFields: null,
  usernameLowerCase: true,
  profileField: 'profile',
  usernameField: 'username',
  emailField: 'email',
  hashField: 'hash',
  saltField: 'salt',
  lastLoginField: 'lastLogin',
  lastLogoutField: 'lastLogout',
  limitLoginAttempts: true,
  loginAttemptsField: 'loginAttempts',
  loginAttemptLockTimeField: 'loginAttemptLockTime',
  resetPasswordHashField: 'resetPasswordHash',
  resetPasswordExpirationField: 'resetPasswordExpiration',
  googleIdField: 'googleId',
  facebookIdField: 'facebookId'
};